### ISSUE TITLE
Failed to use this with Brekeke Server Advanced Edition

### ISSUE THREAD

**Issue by dhavaln** [brekekesoftware/brekekephone#195]
We have a Brekeke Server Advanced setup into our private network. The server is running on IP address and using the WebSocket for communication. We have an Web-based phone app that works fine with the server and now we are trying to integrate our React Native application with the Brekeke server but cannot make it work. 

I was checking this repo in the hope that it should work, but we cannot connect to the server after building the app from this repo.

Already used the PJSIP and a few other libraries but was not able to get it connected with the Brekeke server. 
Just to reiterate, the HTML/JS-based web application is working fine with the same Brekeke server.

**Comment by namnm** [comment]
@dhavaln Please contact Brekeke support team, they will be in touch and handle your situation. Thanks
