### ISSUE TITLE
Failed to answer video call

### ISSUE THREAD

**Issue by wevo-ding0215** [brekekesoftware/brekekephone#206]
I am getting this error **JsSIP:ERROR:RTCSession emit "peerconnection:setremotedescriptionfailed" [error:%o] +0ms Failed to set remote offer sdp: Failed to set remote video description send parameters.** when trying to set the remote description for the RTC connection. Do you know what issue that cause this error?

**Comment by namnm** [comment]
@wevo-ding0215 Please contact Brekeke support team at: support@brekeke.jp
Thanks
