### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by abdrahman20** [brekekesoftware/brekekephone#232]
Hi,

when i tried to run using "yarn rn" I got "FAILURE: Build failed with an exception"

Execution failed for task ':tasks'.
> Could not create task ':react-native-notifications:testReactNative60DebugUnitTest'.
   > No signature of method: org.gradle.api.reporting.internal.TaskGeneratedSingleDirectoryReport.enabled() is applicable for argument types: (Boolean) values: [true]

what could be the issue?

**Comment by namnm** [comment]
Simply upgrade the package, or use patch:
https://github.com/wix/react-native-notifications/issues/975
