### ISSUE TITLE
callkeepUuid missing and speaker not working on receive call

### ISSUE THREAD

**Issue by danikhan1994** [brekekesoftware/brekekephone#318]
Hello,
I have an issue while getting a call it shows in log (No incoming call activity for uuid=) where callkeepUuid is empty and it makes a lot of issue to perform calling correctly one of the main issue is speaker because without callkeepUuid speaker will not work for toggling speaker (getCallStore().toggleLoudSpeaker) this is the onpress function in the below function it mentioned if uuid not found just return and without uuid RNCallKeep.toggleAudioRouteSpeaker will not work

@observable isLoudSpeakerEnabled = false
  @action toggleLoudSpeaker = () => {
    if (Platform.OS === 'web') {
      return
    }
    this.isLoudSpeakerEnabled = !this.isLoudSpeakerEnabled
    if (Platform.OS === 'ios') {
      IncallManager.setForceSpeakerphoneOn(this.isLoudSpeakerEnabled)
      return
    }
    const uuid = this.getOngoingCall()?.callkeepUuid
    if (!uuid) {
      return
    }
    RNCallKeep.toggleAudioRouteSpeaker(uuid, this.isLoudSpeakerEnabled)
    BrekekeUtils.setSpeakerStatus(this.isLoudSpeakerEnabled)
  }

**Comment by namnm** [comment]
Fixed on latest master

**Comment by danikhan1994** [comment]
I have tested by building the latest master debug but i still got the same error

**Comment by namnm** [comment]
@danikhan1994 Fix commit for this issue on android merged on 26th Dec:
https://github.com/brekekesoftware/brekekephone/pull/317/files#diff-01142405866ac3f5c51b3393c7b297215fb653106bd566d0df69ca20cfd41295R53
